import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generatePDF = (
  uploadResult,
  recommendation,
  tuning,
  history
) => {
  const doc = new jsPDF();

  // ==========================
  // Title
  // ==========================

  doc.setFontSize(22);
  doc.setTextColor(30, 64, 175);
  doc.text("ModelMatch", 105, 20, { align: "center" });

  doc.setFontSize(14);
  doc.setTextColor(80);
  doc.text(
    "AI Powered AutoML Recommendation Report",
    105,
    30,
    { align: "center" }
  );

  doc.setFontSize(10);
  doc.text(
    `Generated : ${new Date().toLocaleString()}`,
    105,
    40,
    { align: "center" }
  );

  // ==========================
  // Dataset Summary
  // ==========================

  const meta = uploadResult?.data?.meta_features || {};

  autoTable(doc, {
    startY: 50,
    head: [["Dataset Summary", "Value"]],
    body: [
      ["Dataset", uploadResult?.data?.dataset_name || "-"],
      ["Rows", meta.rows || "-"],
      ["Columns", meta.columns || "-"],
      ["Classes", meta.nr_class || "-"],
      ["Missing %", meta.missing_percentage || 0],
    ],
  });

  // ==========================
  // Best Model
  // ==========================

  if (tuning && tuning.length > 0) {
    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 12,
      head: [["Best Model", "Accuracy"]],
      body: [
        [
          tuning[0].model,
          `${(tuning[0].best_score * 100).toFixed(2)}%`,
        ],
      ],
    });

    const params = Object.entries(
      tuning[0].parameters || {}
    ).map(([k, v]) => [k, String(v)]);

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 10,
      head: [["Best Hyperparameter", "Value"]],
      body: params,
    });
  }

  // ==========================
  // Recommendations
  // ==========================

  if (
    recommendation &&
    recommendation.recommendations
  ) {
    doc.addPage();

    const rows = recommendation.recommendations.map(
      (r) => [
        r.model,
        r.dataset,
        (r.score * 100).toFixed(2) + "%",
        r.distance,
      ]
    );

    autoTable(doc, {
      head: [
        [
          "Model",
          "Historical Dataset",
          "Historical Accuracy",
          "Distance",
        ],
      ],
      body: rows,
    });
  }

  // ==========================
  // History
  // ==========================

  if (history && history.length > 0) {
    const rows = history.map((h) => [
      h.model,
      h.dataset_name,
      (h.score * 100).toFixed(2) + "%",
      new Date(h.created_at).toLocaleDateString(),
    ]);

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 10,
      head: [["Model", "Dataset", "Accuracy", "Date"]],
      body: rows,
    });
  }

  // ==========================
  // Footer
  // ==========================

  const pages = doc.internal.getNumberOfPages();

  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);

    doc.setFontSize(10);

    doc.text(
      `Generated by ModelMatch | Page ${i} of ${pages}`,
      105,
      290,
      { align: "center" }
    );
  }

  doc.save("ModelMatch_Report.pdf");
};